apiVersion: v1
kind: Pod
metadata:
  name: my-liveness-app
  namespace: my-ns
  labels:
    environment: test
spec:
  containers:
  - name: my-liveness-con
    image: busybox
    command: ['sh', '-c', "echo Hello !!! && sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      exec:
        command:
        - echo
        - testing
      initialDelaySeconds: 5
      periodSeconds: 5
