kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-rs
  namespace: rs-dep-test
spec:
  replicas: 3
  selector:  
    matchLabels:
      app: nginx
    matchExpressions:
      - {key: environment, operator: In, values: [dev, prod]}
  template:
    metadata:
      labels:
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx-con
        image: nginx
    
