#secret example using env
apiVersion: v1
kind: Pod
metadata:
  name: my-secret-app
  namespace: my-ns
  labels:
    app: myapp
    environment: test
spec:
  containers:
  - name: my-secret-con
    image: busybox
    command: ['sh', '-c', "echo ${MY_PASSWORD} && sleep 1200"]
    resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: dbpass
